create table if not exists countries
(
    code    varchar(16) unique primary key not null,
    country varchar(128)                   not null
);

INSERT INTO countries (code, country)
VALUES ('AF', 'Afghanistan'),
       ('AL', 'Albania'),
       ('DZ', 'Algeria'),
       ('ANB', 'Ancient Belgian'),
       ('ANG', 'Angola'),
       ('ALG', 'Algeria'),
       ('AND', 'Andorra'),
       ('AG', 'Antigua and Barbuda'),
       ('ASC', 'Antarctica'),
       ('AR', 'Argentina'),
       ('AM', 'Armenia'),
       ('ATSSR', 'Armenian Soviet Socialist Republic'),
       ('ATL', 'Atlantis'),
       ('AU', 'Australia'),
       ('AT', 'Austria'),
       ('AUAH', 'Austria-Hungary'),
       ('ATN', 'Austrian Empire'),
       ('AZ', 'Azerbaijan'),
       ('ADR', 'Azerbaijan Democratic Republic'),
       ('BS', 'Bahamas'),
       ('BH', 'Bahrain'),
       ('BD', 'Bangladesh'),
       ('BB', 'Barbados'),
       ('EUS', 'Basque Country'),
       ('BY', 'Belarus'),
       ('BE', 'Belgium'),
       ('BZ', 'Belize'),
       ('BJ', 'Benin'),
       ('BM', 'Bermuda'),
       ('BT', 'Bhutan'),
       ('BOG', 'Bogotá'),
       ('BO', 'Bolivia'),
       ('BA', 'Bosnia and Herzegovina'),
       ('BW', 'Botswana'),
       ('BP', 'Brandenburg-Prussia'),
       ('BR', 'Brazil'),
       ('BRM', 'Brian Moran'),
       ('IO', 'British Indian Ocean Territory'),
       ('BNO', 'British National (Overseas)'),
       ('VG', 'British Virgin Islands'),
       ('BN', 'Brunei'),
       ('BG', 'Bulgaria'),
       ('BNN', 'Burgundian Netherlands'),
       ('BF', 'Burkina Faso'),
       ('BI', 'Burundi'),
       ('KH', 'Cambodia'),
       ('CM', 'Cameroon'),
       ('CA', 'Canada'),
       ('CV', 'Cape Verde'),
       ('CAT', 'Catalonia'),
       ('KY', 'Cayman Islands'),
       ('CF', 'Central African Republic'),
       ('TD', 'Chad'),
       ('CHI', 'Chicago'),
       ('CL', 'Chile'),
       ('CN', 'China'),
       ('CIS', 'Cisleithania'),
       ('CO', 'Colombia'),
       ('KM', 'Comoros'),
       ('CR', 'Costa Rica'),
       ('FLE', 'County of Flanders'),
       ('ROU', 'County of Roussillon'),
       ('HR', 'Croatia'),
       ('CU', 'Cuba'),
       ('CY', 'Cyprus'),
       ('CZ', 'Czech Republic'),
       ('CZOS', 'Czechoslovakia'),
       ('DEP', 'Dakota Estates Park'),
       ('DL', 'Dave Lang'),
       ('DRC', 'Democratic Republic of the Congo'),
       ('DK', 'Denmark'),
       ('DEN', 'Denmark-Norway'),
       ('DJ', 'Djibouti'),
       ('DM', 'Dominica'),
       ('DO', 'Dominican Republic'),
       ('DI', 'Dominion of India'),
       ('DB', 'Duchy of Brunswick'),
       ('DF', 'Duchy of Florence'),
       ('DMS', 'Duchy of Mecklenburg-Schwerin'),
       ('DMR', 'Duchy of Modena and Reggio'),
       ('DW', 'Duchy of Württemberg'),
       ('DG', 'Durango'),
       ('NR', 'Dutch Republic'),
       ('EB', 'Ecclesiastical principality of Basel'),
       ('EC', 'Ecuador'),
       ('EG', 'Egypt'),
       ('SV', 'El Salvador'),
       ('EP', 'Electoral Palatinate'),
       ('EM', 'Electorate of Mainz'),
       ('ENG', 'England'),
       ('GQ', 'Equatorial Guinea'),
       ('EQ', 'Equestria'),
       ('ER', 'Eritrea'),
       ('EE', 'Estonia'),
       ('ET', 'Ethiopia'),
       ('ETE', 'Ethiopian Empire'),
       ('EU', 'Europe'),
       ('FO', 'Faroe Islands'),
       ('FJI', 'Fiji'),
       ('FI', 'Finland'),
       ('FSA', 'First Syrian Republic'),
       ('FL', 'Flanders'),
       ('FF', 'Free City of Frankfurt'),
       ('FR', 'French'),
       ('GAB', 'Gabon'),
       ('GA', 'Galicia'),
       ('WAG', 'Gambia'),
       ('GE', 'Georgia'),
       ('DC', 'German Confederation'),
       ('DDR', 'German Democratic Republic'),
       ('DR', 'German Reich'),
       ('DE', 'Germany'),
       ('GH', 'Ghana'),
       ('GI', 'Gibraltar'),
       ('GS', 'Gilford Yung Gilly Smith'),
       ('GR', 'Greece'),
       ('GL', 'Greenland'),
       ('GCA', 'Grenada'),
       ('GT', 'Guatemala'),
       ('GYE', 'Guayaquil'),
       ('GGY', 'Guernsey'),
       ('GK', 'Guinea'),
       ('GW', 'Guinea-Bissau'),
       ('GUY', 'Guyana'),
       ('HM', 'Habsburg Monarchy'),
       ('HBN', 'Habsburg Netherlands'),
       ('HT', 'Haiti'),
       ('HL', 'Hanseatic League'),
       ('HJ', 'Herodian Kingdom of Judea'),
       ('HRE', 'Holy Roman Empire'),
       ('HN', 'Honduras'),
       ('HK', 'Hong Kong'),
       ('HU', 'Hungary'),
       ('IS', 'Iceland'),
       ('IN', 'India'),
       ('ID', 'Indonesia'),
       ('IRN', 'Iran'),
       ('IRK', 'Iranian Kurdistan'),
       ('IRQ', 'Iraq'),
       ('IRL', 'Ireland'),
       ('IM', 'Isle of Man'),
       ('IL', 'Israel'),
       ('IA', 'Italian Argentines'),
       ('IT', 'Italy'),
       ('CI', 'Ivory Coast'),
       ('JA', 'Jamaica'),
       ('JP', 'Japan'),
       ('YN', 'Jellystone National Park'),
       ('JEY', 'Jersey'),
       ('JOR', 'Jordan'),
       ('JUD', 'Judah'),
       ('KAR', 'Karachi'),
       ('KZ', 'Kazakhstan'),
       ('KE', 'Kenya'),
       ('KJH', 'Kim Ji Hyun'),
       ('BAY', 'Kingdom of Bavaria'),
       ('HA', 'Kingdom of Hanover'),
       ('H', 'Kingdom of Hungary'),
       ('I', 'Kingdom of Italy'),
       ('KK', 'Kingdom of Kartli-Kakheti'),
       ('N', 'Kingdom of Naples'),
       ('NA', 'Kingdom of Navarre'),
       ('PRU', 'Kingdom of Prussia'),
       ('SX', 'Kingdom of Saxony'),
       ('SC', 'Kingdom of Scotland'),
       ('SER', 'Kingdom of Serbia'),
       ('KSP', 'Kingdom of Sicily (1734-1816)'),
       ('W', 'Kingdom of Württemberg'),
       ('JUG', 'Kingdom of Yugoslavia'),
       ('2S', 'Kingdom of the Two Sicilies'),
       ('KIR', 'Kiribati'),
       ('KOR', 'Korea'),
       ('RKS', 'Kosovo'),
       ('KWT', 'Kuwait'),
       ('KG', 'Kyrgyzstan'),
       ('V', 'Land of Valencia'),
       ('HES', 'Landgraviate of Hesse-Darmstadt'),
       ('LA', 'Laos'),
       ('LV', 'Latvia'),
       ('RL', 'Lebanon'),
       ('LS', 'Lesotho'),
       ('LB', 'Liberia'),
       ('LAR', 'Libya'),
       ('LI', 'Liechtenstein'),
       ('LT', 'Lithuania'),
       ('LU', 'Luxembourg'),
       ('MK', 'Macedonia'),
       ('MG', 'Madagascar'),
       ('MW', 'Malawi'),
       ('MAL', 'Malaysia'),
       ('MV', 'Maldives'),
       ('RMM', 'Mali'),
       ('M', 'Malta'),
       ('MB', 'Margraviate of Brandenburg'),
       ('MR', 'Margraviate of Moravia'),
       ('RI', 'Marshall Islands'),
       ('MHD', 'Mashhad'),
       ('RIM', 'Mauritania'),
       ('MS', 'Mauritius'),
       ('MEX', 'Mexico'),
       ('MD', 'Moldova'),
       ('MC', 'Monaco'),
       ('MON', 'Mongolia'),
       ('MNE', 'Montenegro'),
       ('MSR', 'Montserrat'),
       ('MA', 'Morocco'),
       ('MZ', 'Mozambique'),
       ('MM', 'Myanmar'),
       ('NAM', 'Namibia'),
       ('GER', 'Nazi Germany'),
       ('NP', 'Nepal'),
       ('NL', 'Netherlands'),
       ('ANT', 'Netherlands Antilles'),
       ('NYC', 'New York City'),
       ('NZ', 'New Zealand'),
       ('NZCC', 'New Zealand Cycle Classic'),
       ('NIC', 'Nicaragua'),
       ('RN', 'Nigeria'),
       ('NGR', 'Nigerian'),
       ('NK', 'North Korea'),
       ('NCP', 'Northern Cyprus'),
       ('NIR', 'Northern Ireland'),
       ('NO', 'Norway'),
       ('OAX', 'Oaxaca State'),
       ('OKI', 'Okinawa Prefecture'),
       ('OM', 'Oman'),
       ('OO', 'Orb Union'),
       ('OE', 'Ottoman Empire'),
       ('PAHL', 'Pahlavi Dynasty'),
       ('PK', 'Pakistan'),
       ('PSE', 'Palestine'),
       ('PA', 'Panama'),
       ('PS', 'Papal States'),
       ('PNG', 'Papua New Guinea'),
       ('PY', 'Paraguay'),
       ('PE', 'Peru'),
       ('PH', 'Philippines'),
       ('PL', 'Poland'),
       ('PLC', 'Polish–Lithuanian Commonwealth'),
       ('PAP', 'Port-au-Prince'),
       ('POR', 'Portland'),
       ('PT', 'Portugal'),
       ('PBL', 'Prince-Bishopric of Liège'),
       ('PR', 'Puerto Rico'),
       ('Q19236425', 'Q19236425'),
       ('QA', 'Qatar'),
       ('QD', 'Qing dynasty'),
       ('BAH', 'Republic of Bosnia and Herzegovina'),
       ('RC', 'Republic of China'),
       ('RF', 'Republic of Florence'),
       ('RG', 'Republic of Genoa'),
       ('RT', 'Republic of Tatarstan'),
       ('RV', 'Republic of Venice'),
       ('RH', 'Rhodesia'),
       ('RO', 'Romania'),
       ('RUS', 'Russia'),
       ('RE', 'Russian Empire'),
       ('RSFSR', 'Russian Soviet Federative Socialist Republic'),
       ('RWA', 'Rwanda'),
       ('KN', 'Saint Kitts and Nevis'),
       ('WL', 'Saint Lucia'),
       ('VCT', 'Saint Vincent and the Grenadines'),
       ('WS', 'Samoa'),
       ('SAT', 'San Antonio Texas'),
       ('RSM', 'San Marino'),
       ('STP', 'Sao Tome and Principe'),
       ('SA', 'Saudi Arabia'),
       ('SEE', 'Saxe-Eisenach'),
       ('SWE', 'Saxe-Weimar-Eisenach'),
       ('SCO', 'Scotland'),
       ('SFE', 'Second French Empire'),
       ('SP', 'Second Polish Republic'),
       ('SEL', 'Seljuk Empire'),
       ('SN', 'Senegal'),
       ('SRB', 'Serbia'),
       ('SM', 'Serbia and Montenegro'),
       ('17P', 'Seventeen Provinces'),
       ('SY', 'Seychelles'),
       ('SL', 'Sierra Leone'),
       ('SG', 'Singapore'),
       ('SK', 'Slovakia'),
       ('SLO', 'Slovenia'),
       ('SFRY', 'Socialist Federal Republic of Yugoslavia'),
       ('SR', 'Socialist Republic of Romania'),
       ('SB', 'Solomon Islands'),
       ('SOM', 'Somali Democratic Republic'),
       ('SO', 'Somalia'),
       ('ZA', 'South Africa'),
       ('SS', 'South Sudan'),
       ('SU', 'Soviet Union'),
       ('ES', 'Spain'),
       ('BENL', 'Spanish Netherlands'),
       ('LK', 'Sri Lanka'),
       ('STR', 'Strašice'),
       ('SD', 'Sudan'),
       ('SZ', 'Swaziland'),
       ('SE', 'Sweden'),
       ('CH', 'Switzerland'),
       ('SYR', 'Syria'),
       ('SAPMI', 'Sápmi'),
       ('TW', 'Taiwan'),
       ('TJ', 'Tajikistan'),
       ('TZ', 'Tanzania'),
       ('TEH', 'Tehran'),
       ('TA', 'Tel Aviv'),
       ('TX', 'Texas'),
       ('TH', 'Thailand'),
       ('GM', 'The Gambia'),
       ('TL', 'Timor-Leste'),
       ('TY', 'Todd Yannacone'),
       ('TG', 'Togo'),
       ('TK', 'Tokyo'),
       ('TO', 'Tonga'),
       ('TOR', 'Torreón'),
       ('TT', 'Trinidad and Tobago'),
       ('TN', 'Tunisia'),
       ('TR', 'Turkey'),
       ('TRNC', 'Turkish Republic of Northern Cyprus'),
       ('TM', 'Turkmenistan'),
       ('TV', 'Tuvalu'),
       ('VI', 'U.S. Virgin Islands'),
       ('UG', 'Uganda'),
       ('UA', 'Ukraine'),
       ('UPR', 'Ukrainian People''s Republic'),
       ('USSR', 'Ukrainian Soviet Socialist Republic'),
       ('SW', 'Union between Sweden and Norway'),
       ('AE', 'United Arab Emirates'),
       ('GB', 'United Kingdom'),
       ('UK', 'United Kingdom of Great Britain and Ireland'),
       ('US', 'United States'),
       ('USA', 'United States of America'),
       ('URU', 'Uruguay'),
       ('UZ', 'Uzbekistan'),
       ('VU', 'Vanuatu'),
       ('VA', 'Vatican City'),
       ('VE', 'Veldhuizen'),
       ('VEN', 'Venezuela'),
       ('NSP', 'Viceroyalty of New Spain'),
       ('VP', 'Viceroyalty of Peru'),
       ('RVP', 'Viceroyalty of the Río de la Plata'),
       ('VN', 'Vietnam'),
       ('WLS', 'Wales'),
       ('WR', 'Weimar Republic'),
       ('WGER', 'West Germany'),
       ('WSAH', 'Western Sahara'),
       ('WU', 'Wu'),
       ('YE', 'Yemen'),
       ('YUG', 'Yugoslavia'),
       ('ZM', 'Zambia'),
       ('ZAN', 'Zanzibar'),
       ('ZW', 'Zimbabwe'),
       ('ZAR', 'Zárate');